[versions]
agp = "8.13.1"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.1"
constraintlayout = "2.1.4"
exoplayerCoreVer = "2.19.1"
exoplayerUiVer = "2.19.1"
exoplayerDashVer = "2.19.1"
exoplayerHlsVer = "2.19.1"
verticalSeekbarBar = "1.2.7"
doubleTapPlayerView = "1.0.4"
fragment = "1.8.2"
cronetEmbedded = "119.6045.31"
smoothbottombar = "1.7.9"
sdp = "1.1.0"
ssp = "1.1.0"
lottie = "6.1.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
exoplayerCore = {group = "com.google.android.exoplayer", name = "exoplayer", version.ref = "exoplayerCoreVer"}
exoplayerUi = {group = "com.google.android.exoplayer", name = "exoplayer-ui", version.ref = "exoplayerUiVer"}
exoplayerDash = {group = "com.google.android.exoplayer", name = "exoplayer-dash", version.ref = "exoplayerDashVer"}
exoplayerHls = {group = "com.google.android.exoplayer", name = "exoplayer-hls", version.ref = "exoplayerHlsVer"}
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
verticalSeekbar = {group = "com.github.lukelorusso", name = "VerticalSeekBar", version.ref = "verticalSeekbarBar"}
doubleTapPlayerView = {group = "com.github.vkay94", name = "DoubleTapPlayerView", version.ref = "doubleTapPlayerView"}
cronet-embedded = { group = "org.chromium.net", name = "cronet-embedded", version.ref = "cronetEmbedded" }
smoothbottombar = { module = "com.github.ibrahimsn98:SmoothBottomBar", version.ref = "smoothbottombar" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdp" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "ssp" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

